logo: /assets/img/full_portrait_clean.png
title: Corbin Stone Diaz
description: Data Science & Math Major <br />@ Northwestern University
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
url: "https://corbindiaz.github.io/"
color-scheme: auto

include:
  - assets
  - pages
  - "/assets/css/custom-styles.css"

plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-seo-tag

platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/corbin-diaz-6a7863281/
  - name: Substack
    icon: <i class="fa-solid fa-newspaper"></i>
    link: https://substack.com/@corbindiaz
  - name: Email
    icon: <i class="fa fa-envelope" aria-hidden="true"></i>
    link: mailto:corbindiaz2026@u.northwestern.edu

navigation:
  - name: About
    link: /index.html
  - name: Projects
    link: /pages/projects.html
  - name: Research
    link: /pages/research.html
  - name: Teaching
    link: /pages/teaching.html
