remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jemoji

logo: /assets/img/logo.png

title: Corbin Stone Diaz
description: Data Science & Math Major @ Northwestern University
email: corbindiaz2026@u.northwestern.edu
color-scheme: auto

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/corbindiaz
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/corbin-diaz-6a7863281/
  - name: Email
    icon: <i class="fa fa-envelope" aria-hidden="true"></i>
    link: mailto:corbindiaz2026@u.northwestern.edu

navigation:
  - name: About
    link: ./index.html
  - name: Projects
    link: ./projects.html
