remote_theme: vaibhavvikas/jekyll-theme-minimalistic

## logo: /img/github_profile_image.jpeg

title: Corbin Stone Diaz
description: Data Science and Mathematics Major @ Northwestern University
color-scheme: auto

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/corbindiaz
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/corbin-diaz-6a7863281/

navigation:
  - name: Home
    link: ./index.html
  - name: Projects
    link: ./projects.html
