remote_theme: vaibhavvikas/jekyll-theme-minimalistic
baseurl: "https://corbindiaz.github.io/docs"

logo: /assets/img/logo.png


title: Corbin Stone Diaz
description: Data Science & Math Major <br />@ Northwestern University
color-scheme: auto

github: false

include:
  - assets

exclude: []

defaults:
  - scope:
      path: "assets/*"
    values:
      layout: nil

plugins:
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/corbindiaz
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/corbin-diaz-6a7863281/
  - name: Email
    icon: <i class="fa fa-envelope" aria-hidden="true"></i>
    link: mailto:corbindiaz2026@u.northwestern.edu

navigation:
  - name: About
    link: ./index.html
  - name: Projects
    link: ./projects.html
